### PR TITLE
Update changelog for v2.3.10

### PR DESCRIPTION
**Pull request by DMcKinnon-mdsol**
This PR updates the changelog for the recent change to support rails 4 apps.

@sakhtermdsol @cwhite-mdsol please review.

### CODE REVIEW

**Comment by rbuenviaje-mdsol** [comment]
It might be good to continue using the 2.3.9.x since this is a fork off of a public gem. We've done a lot of changes to this gem though, so I don't know if the original will ever come back in... @sakhtermdsol thoughts?

**Comment by rbuenviaje-mdsol** [comment]
Please update chttps://github.com/mdsol/rubycas-client/blob/develop/lib/casclient/version.rb if we go with the .10 change

**Comment by DMcKinnon-mdsol** [comment]
Haha that file has not been updated in...awhile. Will do. @sakhtermdsol? Stick with `2.3.10`? I say yes.

**Comment by sakhtermdsol** [comment]
Yeah I don't think we'll ever merge in the original

**Pull request merged**
