### PR TITLE
MCC-118915 add before method to filter class

### PR DESCRIPTION
**Pull request by dyg2104MD**
My epro-tests are failing b/c the before method is missing from the filter class in rubycas-client. 

i found the source code here http://www.rubydoc.info/github/rubycas/rubycas-client/CASClient/Frameworks/Rails/Filter#before-class_method

and added it back. apparently the before method has to be called if we are using a before filter with rubycas-client somewhere like here https://github.com/mdsol/epro-app/blob/develop/app/controllers/web_controller.rb#L2

@mdsol/team-63

### CODE REVIEW

**Comment by rbuenviaje-mdsol** [comment]
Same as https://github.com/mdsol/rubycas-client/pull/21, but the outstanding comment there hasn't been addressed. Please update the change log and version.

**Comment by dyg2104MD** [comment]
@rbuenviaje-mdsol updated the change log and version

cc @jcarres-mdsol

**Comment by pmavinkurve-mdsol** [comment]
Not the right place for this discussion. But adding a mental reminder to myself to ping folks about this. 
is it on our radar to eventually retire this client in favor of the `rubycas/rubycas-client-rails`?  That would be sweet, but i haven't compared the two.

**Comment by pmavinkurve-mdsol** [comment]
Thank you @dyg2104MD for fixing this!

**Comment by rbuenviaje-mdsol** [comment]
Cool LGTM

**Comment by sakhtermdsol** [comment]
LGTM Thanks!

**Pull request merged**
