### PR TITLE
Fix for apps using rails 5.1 +

### PR DESCRIPTION
**Pull request by kaspatel-mdsol**
Context:

I'm upgrading Patient Cloud Settings to Rails 5.2. While ad-hoc testing, I was unable to login and set session which lets us enter the app. When the session was being set or read, I got the following error `TypeError - can't quote Rack::Session::SessionId`

I temporarily fixed it on my local gem, then another error came up which was regarding that `MethodError - NO env method on Action Controller`. 

Fixes:

- Use patch provided for quote error [here](https://github.com/rails/rails/issues/38039)
- Use ActionController.Request#env instead of ActionController#env

PS:

I'm comparing with `master` as `develop` is not up-to-date with `master`. Also, v3.0.3 which we are using is based on the master branch

### CODE REVIEW

**Comment by cwhite-mdsol** [comment]
can you make this PR to develop please, all the discrepancies that you noted are only merges of develop into master

**Comment by kaspatel-mdsol** [comment]
> can you make this PR to develop please, all the discrepancies that you noted are only merges of develop into master

Done. It's based on develop now.

**Comment by DMcKinnon-mdsol** [comment]
Your build is failing.

Should some tests be updated?

**Comment by kaspatel-mdsol** [comment]
> The build is failing. Is that expected
> 
> Should some tests be updated?

Tests are not even running. Bundle Install itself fails on CI

**Comment by kaspatel-mdsol** [comment]
Hey guys, I thought I made a fresh branch out of the latest `develop` and close this PR as it had multiple changes apart from mine. Also, I thought it might fix CI issues.

I've opened a new PR https://github.com/mdsol/rubycas-client/pull/46 .Please refer to that. Same changes as before

**Pull request closed without merging**
