### PR TITLE
[MCC-192923] Create An auto session timeout Method

### PR DESCRIPTION
**Pull request by cwhite-mdsol**
This PR creates an auto session timeout method to pass the timeout value or the default timeout value back to an application.

rspecs
Finished in 0.60356 seconds
171 examples, 0 failures

@sakhtermdsol @HonoreDB

### CODE REVIEW

**Comment by HonoreDB** [comment]
Cool!

This does look like `@@timeout` ends up being shared across users, which might not be what everybody wants. I'm rusty on how state ends up getting passed around here--is it possible to access the extra_attributes directly from inside the auto_session_timeout method?

**Comment by cwhite-mdsol** [comment]
@HonoreDB added use of extra attributes in https://github.com/mdsol/rubycas-client/commit/5ebe347a24d416367dcb060eaf1cf8f1cb5682f7

**Comment by HonoreDB** [comment]
Nice. Would you mind adding an rspec for the method, if that's feasible? Otherwise, looks good to me.

**Comment by sakhtermdsol** [comment]
A spec would be nice. LGTM as well!

**Pull request merged**
